# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_auto_20160417_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
