# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 01:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_resposta_gateway_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='resposta_gateway',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True, verbose_name='Resposta da Mundipagg'),
        ),
    ]
