# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_resposta_gateway_propriedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 27, 1, 42, 9, 429624, tzinfo=utc), verbose_name='Atualizado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 27, 1, 42, 11, 180480, tzinfo=utc), verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
