# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0005_change_meta_options_on_doacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ('-criado_em',), 'verbose_name': 'doação', 'verbose_name_plural': 'doações'},
        ),
        migrations.AddField(
            model_name='doacao',
            name='notificacao_gateway',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True, verbose_name='Notificação da Mundipagg'),
        ),
    ]
